### ISSUE TITLE
noruko.org down

### ISSUE THREAD

**Issue by matiaskorhonen** [rubynl/noruko.org#14]
I noticed that noruko.org is no longer online. What would you think of preserving the site on an Euruko subdomain (`noruko.euruko.org`)  for posterity? Or alternatively a RubyNL subdomain, if that feels more appropriate…

**Comment by arnoFleming** [comment]
Thanks @matiaskorhonen. We're looking into it. 😬

**Comment by tombruijn** [comment]
@matiaskorhonen it lives (again)! That's a mess up on our part, but it should be good now for another year. We can talk about moving it there, saves us the hassle of having to pay for the domain that's mostly unused. I just now had to paid for the domain unfortunately, so it's a bit of a waste, but that way we can at least set up a redirect that search engines can pick up.

How do you want to handle it?

> Or alternatively a RubyNL subdomain, if that feels more appropriate…

Actually, I like this idea too.

**Comment by tombruijn** [comment]
I've moved the website to https://noruko.rubynl.org/ and set up a redirector for the noruko.org domain. That way we can have it lapse if we don't need it anymore next year.
